# Generated by Django 6.0.6 on 2026-07-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='jti',
            field=models.UUIDField(db_index=True, unique=True),
        ),
    ]
